/* import external modules */
import Head from 'next/head'
import Image from 'next/image'

/* import internal modules */
import styles from '../src/styles/Home.module.css'
import HomeLayout from '../src/modules/home/templates/HomeLayout'

/** @description This is a functional home component
 *  @version 1.0.0
 *  @since 14/07/2022
 *  @author Jaime Andrés Gómez Gutiérrez <g.gutierrez.j.andres@gmail.com>
 *
 *  @function
 *  @name Home
 *  @returns {Component} Returns the home component
 **/

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>boilerplate-e-commerce-materio-mui-react-nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeLayout />

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
